### PR TITLE
Remove support for EOL Python version (3.7)

### PR DESCRIPTION
**Pull request by ulgens**
Relates to https://github.com/janluke/cloup/issues/176

### CODE REVIEW

**Comment by janluke** [comment]
Thanks for the PR! Can you remove usages of typing_extensions?

**Comment by ulgens** [comment]
Of course, let me check. I'll update the PR.

**Comment by ulgens** [comment]
@janluke I have two questions/cases:
* The code uses `Concatenate` and it is only included in Python after 3.10. 3.8 and 3.9 tess still need `typing_extensions` unless you have a quick recommendation to replace it.
* I tried to update requirement lock files for Python 3.8 but had no luck. Working under latest mac OS, using Python 3.8.19 with pyenv, gives `AttributeError: cython_sources` similar to https://stackoverflow.com/questions/77490435/attributeerror-cython-sources . Instructions from https://github.com/janluke/cloup/blob/master/CONTRIBUTING.rst ends up with the same issue.

**Comment by ulgens** [comment]
@janluke Ping 🌺

**Comment by janluke** [comment]
Looks good. Thanks for the PR!

**Pull request merged**
