### PR TITLE
Make cloup pass mypy --strict

### PR DESCRIPTION
**Pull request by janluke**
@alexreg can you please check now?

### CODE REVIEW

**Comment by alexreg** [comment]
@janluke Same problem, I'm afraid. (Exactly the same errors as in [this comment](https://github.com/janluke/cloup/pull/121#issuecomment-1138008727).)

**Comment by janluke** [comment]
@alexreg Are you sure you are running mypy against this branch of Cloup? I've just forked your repo and run `mypy --strict` against `master`. I only got 3 errors related to your code (not Cloup) that I fixed in a few seconds.
```shell
(venv) PS H:\Repo\_forks\alexreg-typer> mypy --version     
mypy 0.960 (compiled: yes)
(venv) PS H:\Repo\_forks\alexreg-typer> mypy --strict typer
Success: no issues found in 12 source files
```

I've not checked if you added `type: ignore` everywhere though.

**Comment by alexreg** [comment]
Yep, definitely running it against your branch. I'll experiment tomorrow if I can.

**Comment by alexreg** [comment]
@janluke I can confirm exactly the same errors are occurring on my branch still, using your latest version of cloup. Maybe for you it passes because you have `strict = False` in your `mypy.ini` file? Not sure.

As for `type: ignore`, I'm not quite sure what you mean. The whole point of type hints is that you should not have to add these, in theory.

**Comment by janluke** [comment]
> @janluke I can confirm exactly the same errors are occurring on my branch still, using your latest version of cloup. 

You mean this branch, right? Of course master will give errors.

> As for type: ignore, I'm not quite sure what you mean. The whole point of type hints is that you should not have to add these, in theory.

I was just wondering if I maybe didn't see any error because you added `type: ignore` comments. That's not the case.

> Maybe for you it passes because you have strict = False in your mypy.ini file? Not sure.

Even if that was the case (and it's not), the CLI argument overrides settings. As you can see, I run mypy passing `--strict` and can't replicate the errors you're seeing.

**Comment by alexreg** [comment]
@janluke Yeah, this branch. Re the `ini` file, I agree, I just thought maybe its behaviour was weird...

I deleted my `mypy.ini` file, and get a few more telling errors.
```console
typer/models.py:18: error: Cannot find implementation or library stub for module named "cloup"                                          
typer/models.py:22: error: Cannot find implementation or library stub for module named "cloup.constraints"                              
typer/params.py:4: error: Cannot find implementation or library stub for module named "cloup"                                           
typer/params.py:5: error: Cannot find implementation or library stub for module named "cloup.constraints"
typer/core.py:23: error: Cannot find implementation or library stub for module named "cloup"
typer/main.py:24: error: Cannot find implementation or library stub for module named "cloup"
typer/main.py:49: error: Cannot find implementation or library stub for module named "cloup.constraints"
```

I'm not sure if you need to add `py.typed` to `package_data` in your `setup.py` file, but in any case, that does not help here.

**Comment by janluke** [comment]
Every file you see in the repo (and so `py.typed`) is included in the distribution because I'm using `setuptools-scm`. Since I cannot reproduce, there's something wrong with either my or your environment, or it may depend on the version of mypy. Can you run the following?

```shell
pip install -U --force-reinstall git+https://github.com/janluke/cloup.git@strict-typing#egg=cloup
pip install -U mypy
mypy --strict typer
```

**Comment by alexreg** [comment]
@janluke Ah, fair enough. Anyway, I tried running the above, thanks. But unfortunately no difference in result. Normally I would say my installation has a problem, but given that the type hints for Click work fine, I am more doubtful...

**Comment by alexreg** [comment]
@janluke Agh, I see what was happening now! Homebrew can be a bit annoying sometimes... it was giving me the Python 3.9 interpreter but the Python 3.10 version of mypy. Sorry for wasting your time. It now works fine for me. I appreciate you adding this anyway... feel free to merge, of course.

**Comment by janluke** [comment]
No worries :)

**Pull request merged**
