### PR TITLE
Made Cloup compatible with MyPy strict mode (when used as a dependency)

### LINKED ISSUE #117: Mypy fails in strict mode
#### Bug description
Mypy fails to type-check code that uses Cloup, when in strict mode.
(Note, this is in contrast with Click, which Mypy has no problem with.)

#### To Reproduce
1. Install Cloup, e.g., using `pip3 install cloup`.
2. Create file `foo.py` with the following contents.
```python3
import cloup

class Context(cloup.Context):
    pass
```
3. Run `mypy --strict foo.py`.
4. Observe errors in output.5. 
```console
foo.py:4: error: Name "cloup.Context" is not defined
foo.py:4: error: Class cannot subclass "Context" (has type "Any")
Found 2 errors in 1 file (checked 1 source file)
```

#### Expected behavior
Mypy should not give any errors.

#### Versions
macOS 12.3.1
Python 3.9.12
Cloup 0.14.0

### PR DESCRIPTION
**Pull request by janluke**
Fixes #117.

@alexreg Let me know if this fixes your issue and if you have any other issue with strict mode.

### CODE REVIEW

**Comment by alexreg** [comment]
Thanks for looking into this. Afraid not, however. Here's the output:
```console
$ mypy --strict cloup
cloup/typing.py:22: error: Missing type parameters for generic type "Callable"
cloup/typing.py:25: error: Missing type parameters for generic type "Callable"
cloup/formatting/sep.py:156: error: Function is missing a type annotation
cloup/formatting/sep.py:167: error: Function is missing a type annotation
cloup/_util.py:24: error: Function is missing a type annotation
cloup/_util.py:28: error: Function is missing a return type annotation
cloup/_util.py:33: error: Function is missing a type annotation for one or more arguments
cloup/_util.py:38: error: Function is missing a type annotation for one or more arguments
cloup/_util.py:71: error: Function is missing a type annotation
cloup/_util.py:99: error: Function is missing a type annotation
cloup/_util.py:104: error: Incompatible types in assignment (expression has type "Type[ValueError]", variable has type "Optional[Type[TypeError]]")
cloup/_util.py:114: error: Function is missing a type annotation
cloup/_util.py:118: error: Function is missing a type annotation
cloup/_util.py:127: error: Function is missing a type annotation
cloup/_util.py:128: error: "FrozenSpaceMeta" has no attribute "_dict"
cloup/_util.py:134: error: Function is missing a return type annotation
cloup/_util.py:134: note: Use "-> None" if function does not return a value
cloup/_util.py:139: error: Missing type parameters for generic type "dict"
cloup/constraints/common.py:23: error: Returning Any from function declared to return "bool"
cloup/constraints/common.py:84: error: Function is missing a type annotation for one or more arguments
cloup/constraints/common.py:91: error: Function is missing a type annotation for one or more arguments
cloup/constraints/common.py:95: error: Function is missing a type annotation for one or more arguments
cloup/styling.py:85: error: Function is missing a return type annotation
cloup/styling.py:95: error: Function is missing a return type annotation
cloup/styling.py:150: error: Missing type parameters for generic type "dict"
cloup/constraints/_core.py:53: error: Function is missing a type annotation
cloup/constraints/_core.py:89: error: Function is missing a return type annotation
cloup/constraints/_core.py:112: error: Function is missing a type annotation for one or more arguments
cloup/constraints/_core.py:149: error: Returning Any from function declared to return "None"
cloup/constraints/_core.py:211: error: Function is missing a type annotation
cloup/constraints/_core.py:212: error: Call to untyped function "class_name" in typed context
cloup/constraints/_core.py:237: error: Function is missing a type annotation
cloup/constraints/_core.py:245: error: Function is missing a return type annotation
cloup/constraints/_core.py:249: error: Function is missing a type annotation for one or more arguments
cloup/constraints/_core.py:259: error: Function is missing a return type annotation
cloup/constraints/_core.py:269: error: Function is missing a type annotation for one or more arguments
cloup/constraints/_core.py:346: error: Function is missing a return type annotation
cloup/constraints/_core.py:356: error: Function is missing a type annotation
cloup/constraints/_core.py:357: error: Call to untyped function "make_one_line_repr" in typed context
cloup/constraints/_core.py:370: error: Function is missing a type annotation for one or more arguments
cloup/constraints/_core.py:387: error: Function is missing a return type annotation
cloup/constraints/_core.py:390: error: Function is missing a type annotation
cloup/constraints/_core.py:400: error: Function is missing a return type annotation
cloup/constraints/_core.py:436: error: Function is missing a return type annotation
cloup/constraints/_core.py:446: error: Function is missing a type annotation
cloup/constraints/_core.py:466: error: Function is missing a return type annotation
cloup/constraints/_core.py:476: error: Function is missing a type annotation
cloup/constraints/_core.py:492: error: Function is missing a return type annotation
cloup/constraints/_core.py:504: error: Function is missing a type annotation
cloup/formatting/_formatter.py:116: error: Call to untyped function "check_positive_int" in typed context
cloup/formatting/_formatter.py:117: error: Call to untyped function "check_positive_int" in typed context
cloup/formatting/_formatter.py:165: error: Redundant cast to "int"
cloup/formatting/_formatter.py:252: error: Unused "type: ignore" comment
cloup/formatting/_formatter.py:341: error: Function is missing a type annotation
cloup/formatting/_formatter.py:363: error: Call to untyped function "write_row" in typed context
cloup/formatting/_formatter.py:367: error: Call to untyped function "write_row" in typed context
cloup/formatting/_formatter.py:393: error: Function is missing a type annotation
cloup/constraints/_support.py:30: error: Function is missing a type annotation for one or more arguments
cloup/constraints/_support.py:43: error: Function is missing a type annotation
cloup/constraints/_support.py:86: error: Function is missing a type annotation
cloup/constraints/_support.py:107: error: Function is missing a return type annotation
cloup/constraints/_support.py:107: note: Use "-> None" if function does not return a value
cloup/constraints/_support.py:110: error: Function is missing a return type annotation
cloup/constraints/_support.py:124: error: Function is missing a type annotation for one or more arguments
cloup/constraints/_support.py:145: error: Unused "type: ignore" comment
cloup/constraints/_support.py:179: error: Call to untyped function "check_consistency" in typed context
cloup/constraints/_support.py:191: error: Returning Any from function declared to return "Parameter"
cloup/constraints/_support.py:198: error: Function is missing a type annotation for one or more arguments
cloup/constraints/_support.py:214: error: Function is missing a type annotation for one or more arguments
cloup/constraints/conditions.py:50: error: Function is missing a return type annotation
cloup/constraints/conditions.py:66: error: Function is missing a type annotation
cloup/constraints/conditions.py:67: error: Call to untyped function "_public_fields" in typed context
cloup/constraints/conditions.py:69: error: Function is missing a return type annotation
cloup/constraints/conditions.py:72: error: Function is missing a type annotation
cloup/constraints/conditions.py:74: error: Call to untyped function "_public_fields" in typed context
cloup/constraints/conditions.py:115: error: Function is missing a type annotation
cloup/constraints/conditions.py:174: error: Function is missing a return type annotation
cloup/constraints/conditions.py:179: error: Function is missing a return type annotation
cloup/constraints/conditions.py:215: error: Function is missing a return type annotation
cloup/constraints/conditions.py:253: error: Function is missing a return type annotation
cloup/constraints/conditions.py:275: error: Returning Any from function declared to return "bool"
cloup/_sections.py:57: error: Function is missing a return type annotation
cloup/_sections.py:106: error: Function is missing a type annotation for one or more arguments
cloup/_sections.py:133: error: Function is missing a type annotation
cloup/_sections.py:155: error: Function is missing a type annotation for one or more arguments
cloup/_sections.py:187: error: Call to untyped function "_add_command_to_section" in typed context
cloup/constraints/_conditional.py:65: error: Function is missing a return type annotation
cloup/_context.py:13: error: Missing type parameters for generic type "dict"
cloup/_context.py:67: error: Function is missing a type annotation for one or more arguments
cloup/_option_groups.py:63: error: Function is missing a type annotation for one or more arguments
cloup/_option_groups.py:84: error: Function is missing a type annotation for one or more arguments
cloup/_option_groups.py:88: error: Function is missing a type annotation for one or more arguments
cloup/_option_groups.py:118: error: Function is missing a type annotation for one or more arguments
cloup/_option_groups.py:133: error: Unused "type: ignore" comment
cloup/_option_groups.py:305: error: Function is missing a type annotation
cloup/_option_groups.py:342: error: Argument "options" to "_option_group" has incompatible type "Tuple[Any, ...]"; expected "Callable[[Any], Any]"
cloup/_option_groups.py:344: error: Argument "options" to "_option_group" has incompatible type "Tuple[Any, ...]"; expected "Callable[[Any], Any]"
cloup/_option_groups.py:363: error: Function is missing a type annotation
cloup/_option_groups.py:367: error: No overload variant of "reversed" matches argument type "Callable[[F], F]"
cloup/_option_groups.py:367: note: Possible overload variants:
cloup/_option_groups.py:367: note:     def [_T] __init__(self, Reversible[_T]) -> reversed[_T]
cloup/_option_groups.py:367: note:     def [_T] __init__(self, SupportsLenAndGetItem[_T]) -> reversed[_T]
cloup/_option_groups.py:377: error: "Option" has no attribute "group"
cloup/_option_groups.py:380: error: "Option" has no attribute "group"
cloup/_commands.py:66: error: Function is missing a type annotation for one or more arguments
cloup/_commands.py:79: error: Function is missing a type annotation for one or more arguments
cloup/_commands.py:96: error: Function is missing a type annotation
cloup/_commands.py:102: error: Function is missing a type annotation
cloup/_commands.py:105: error: Function is missing a type annotation
cloup/_commands.py:112: error: Call to untyped function "format_aliases" in typed context
cloup/_commands.py:113: error: Call to untyped function "format_help_text" in typed context
cloup/_commands.py:119: error: Call to untyped function "format_epilog" in typed context
cloup/_commands.py:151: error: Function is missing a type annotation for one or more arguments
cloup/_commands.py:263: error: Missing type parameters for generic type "Callable"
cloup/_commands.py:266: error: Unused "type: ignore" comment
cloup/_commands.py:267: error: Function is missing a type annotation for one or more arguments
cloup/_commands.py:284: error: Missing type parameters for generic type "Callable"
cloup/_commands.py:287: error: Function is missing a type annotation
cloup/_commands.py:300: error: Function is missing a type annotation
cloup/_commands.py:301: error: Call to untyped function (unknown) in typed context
cloup/_commands.py:332: error: Missing type parameters for generic type "Callable"
cloup/_commands.py:336: error: Function is missing a type annotation for one or more arguments
cloup/_commands.py:355: error: Missing type parameters for generic type "Callable"
cloup/_commands.py:358: error: Function is missing a type annotation
cloup/_commands.py:371: error: Function is missing a type annotation
cloup/_commands.py:372: error: Call to untyped function (unknown) in typed context
cloup/_commands.py:399: error: Missing type parameters for generic type "Callable"
cloup/_commands.py:404: error: Function is missing a type annotation for one or more arguments
cloup/_commands.py:420: error: Missing type parameters for generic type "Callable"
cloup/_commands.py:425: error: Function is missing a type annotation
cloup/_commands.py:505: error: Function is missing a type annotation
cloup/_commands.py:517: error: Call to untyped function (unknown) in typed context
cloup/_commands.py:549: error: Missing type parameters for generic type "Callable"
cloup/_commands.py:554: error: Function is missing a type annotation for one or more arguments
cloup/_commands.py:573: error: Missing type parameters for generic type "Callable"
cloup/_commands.py:577: error: Function is missing a type annotation
cloup/_commands.py:663: error: Missing type parameters for generic type "Type"
cloup/_params.pyi:10: error: Missing type parameters for generic type "Callable"
cloup/_params.pyi:16: error: Missing type parameters for generic type "tuple"
cloup/_params.pyi:31: error: Function is missing a type annotation for one or more arguments
cloup/_params.pyi:39: error: Function is missing a type annotation for one or more arguments
cloup/_params.pyi:43: error: Function is missing a type annotation for one or more arguments
cloup/_params.pyi:60: error: Function is missing a type annotation for one or more arguments
Found 138 errors in 15 files (checked 23 source files)
```

**Comment by janluke** [comment]
Sorry, I meant if you have any issue when using cloup as a dependency. It's never been my intention to check Cloup with MyPy in strict mode.

**Comment by alexreg** [comment]
@janluke Ah okay, fair. Still some issues, when I run on my repo, however.

```console
typer/models.py:34: error: Class cannot subclass "Context" (has type "Any")
typer/params.py:240: error: Returning Any from function declared to return "Callable[[CommandFunctionType], CommandFunctionType]"
typer/core.py:29: error: Class cannot subclass "Argument" (has type "Any")
typer/core.py:115: error: Returning Any from function declared to return "str"
typer/core.py:129: error: Returning Any from function declared to return "List[CompletionItem]"
typer/core.py:132: error: Class cannot subclass "Option" (has type "Any")
typer/core.py:309: error: Returning Any from function declared to return "List[CompletionItem]"
typer/core.py:333: error: Class cannot subclass "Command" (has type "Any")
typer/core.py:375: error: Class cannot subclass "Group" (has type "Any")
Found 9 errors in 3 files (checked 12 source files)
```

These error messages make clear the types lacking annotations, but don't make clear the functions/attributes lacking annotations, which are: `constraint`, `Argument.metavar`, `Argument.shell_complete`... There are possibly others too.

**Comment by janluke** [comment]
Closing in favour of 
- #122

**Pull request closed without merging**
