### PR TITLE
Feature: parameter group constraints

### PR DESCRIPTION
**Pull request by janluke**
## Main points

- Constraints can be applied to any collection of `Parameter` instances. You can:
    - apply them to option groups defined using `@option_group` (or `OptionGroup`); the constraint help message will be shown in that case;
    - apply them to a set of parameters specified by (destination) name, either using the `@constraint` decorator or using them as a function inside a command callback.

- The core method of a  `Constraint` is `check(params, ctx=None)` which takes either param names or param instances. It raises `ConstraintViolated` if the values assigned to the parameters (defined in `ctx.params`) doesn't satisfy the constraint. It can also raise `UnsatisfiableConstraint` if the constraint is not satisfiable by any assignment of the parameters (see `check_consistency` method).

- Constraints are composable with logical operators `&` and `|`. 

- A `Constraint` has a `help(ctx)` function to generate a help message shown in the option group it is applied on. 

- The help and/or the error message of a constraint can be overridden wrapping the constraint with a `Rephraser` (decorator pattern). You can do this with the method `constraint.rephrased(help, error)`. Both parameters can be a string or a function with specific signature (see code).

- By convention, `cloup` uses camel-case for parametric contraints (e.g. `RequireAtLeast(n)`) and snake-case for non-parametric ones (e.g. `require_all`). Most non-parametric contraints are actual instances defined in terms of other constraints (see example below). In the rare case they need a brand new class, the class is kept private and an instance is assigned to a snake-cased name (e.g. `_RequireAll` -> `require_all`).

An example taken from `cloup` itself:
```python
#: Requires the parameters to be either all set or all unset.
all_or_none = (require_all | accept_none).rephrased(
    help='either all or none should be set',
    error='either all or none of the following options should be set: {param_list}"',
)
```

## Applying a constraint to an option group
This PR introduces a new argument `constraint` for `OptionGroup` and `@option_group`:
```python
from cloup import option_group
from cloup.constraints import RequireAtLeast

@option_group(
    'Group title',
    option('--one', type=int, help='a 1st cool option'),
    option('--two', help='a 2nd cool option'),
    option('--three', help='a 3rd cool option'),
    constraint=RequireAtLeast(1),
)
```

## Usage inside a callback
You just need to create a constraint and then call the method `check(params, ctx=None)` passing the **names** of the parameters in the first argument:
```python
from cloup.constraints import RequireAtLeast

# [...]
def cli(one, two, three,...):
    RequireAtLeast(1)(['one', 'two', 'three'])
```
## Conditional constraints
`If` allows to define constraints that depends on a condition. It takes either the name of a parameter or an instance of `Predicate`. Passing a string `name` is equivalent to passing the predicate `IsSet(name)`. Like constraints, predicates have an associated description and can be composed with logical operators (including also `~`, which is not defined for constraints).

```python
from cloup.constraints import If, require_all, accept_none
from cloup.constraints.conditions import IsSet, Equal

# If parameter with name "tom" is set, then check constraint
If('opt', then=require_all, else_=accept_none)

# Self-explanatory
If(Equal('opt', 'some-value'), then=mutually_exclusive)

# Negating the predicate with ~
If(~Equal('opt', 'some-value'), then=RequireAtLeast(1))
```

## Current limitations
As in click-option-group, it's currently not possible to implement mutually exclusive feature switches. This is not a real limitation of Cloup, as it is a consequence of how Click parses command line arguments.

### CODE REVIEW

**Comment by espdev** [comment]
Thank you for mentioning me. I looked at [the example](https://github.com/janLuke/cloup/blob/constraints/examples/option_groups.py). Your solution looks good and I like your approach to option groups. Constraints functionality looks powerful and flexible. However, it seems to me that explicit constraints checking in decorated function is quite verbose. A user should remember this to explicit call `check_constraint` and duplicate the constraints and option names. It seems to me this can make it harder to maintain the code.

**Comment by janluke** [comment]
@espdev Thank _you_ for commenting! :) 

Not sure if I understood what you mean. A constraint is never duplicated. Do you refer to the fact that you need to pass options by name (strings), right? The point of using constraints inside the callback is to check a group of parameters that don't form an `OptionGroup`. In that case, if you don't use constraints, you still need to write option names in the error message.

```python
#  with constraints:
mutually_exclusive.check(['one', 'six'])

# without
if more_than_one_set(one, six):    # it's not equivalent to (one and six)
    raise UsageError('the following options are mutually exclusive: --one, --six')
```
If you rename `one` to `first` and forgot to update your constraint, you'll get a `KeyError` telling you that `one` is not the name of a CLI parameter. You'll quickly fix it. On the contrary, nobody will remember you to update the error message.

Of course one can work around these issues by using Python variables for constrained options, but I'm not sure it's really worth it. For example:
```python
ONE = 'one'
SIX = 'six'
#...
@option('--one', ONE, ...) 
@option('--six', SIX, ...)
#...
def f(one, six, ...):
    mutually_exclusive.check([ONE, SIX])
```

**Comment by espdev** [comment]
@janLuke 

Then I am not sure if I understood your example correctly. :)

https://github.com/janLuke/cloup/blob/7d2b023bcd0b46724d2028aa3e662c365a5860d1/examples/option_groups.py#L54-L61

> Constraints can be used inside a callback.

This is another way to check constraints?

**Comment by janluke** [comment]
@espdev Yes.

**Pull request merged**
