### PR TITLE
`HelpTheme` as `dataclass` rather than `NamedTuple`

### LINKED ISSUE #159: Change `HelpTheme` type to allow sub-classing
In Click Extra, I have a [default theme lying around](https://github.com/kdeldycke/click-extra/blob/5245748ef30f0a2fba2a7899530c203445907c49/click_extra/colorize.py#L48) that try to extends `cloup.HelpTheme` with additional categories of styles. Like [log-level colors](https://github.com/kdeldycke/click-extra/blob/5245748ef30f0a2fba2a7899530c203445907c49/click_extra/colorize.py#L75-L80) and [other help screen details](https://github.com/kdeldycke/click-extra/blob/5245748ef30f0a2fba2a7899530c203445907c49/click_extra/colorize.py#L82-L92).

The problem is that `cloup.HelpTheme` is a `NamedTuple`. And I cannot easily sub-class it. [As you can see in my code](https://github.com/kdeldycke/click-extra/blob/5245748ef30f0a2fba2a7899530c203445907c49/click_extra/colorize.py#L48), I had to redefine the whole properties and methods.

I also encountered issues with [MyPy which cannot solve references to sub-styles](https://github.com/kdeldycke/click-extra/blob/5245748ef30f0a2fba2a7899530c203445907c49/click_extra/version.py#L66-L67):
```pytb
click_extra/version.py:58: error: Cannot determine type of "default_theme"  [has-type]
        default_package_name_style: IStyle | None = default_theme.invoked_command
                                                    ^~~~~~~~~~~~~
click_extra/version.py:59: error: Cannot determine type of "default_theme"  [has-type]
        default_prog_name_style: IStyle | None = default_theme.invoked_command
                                                 ^~~~~~~~~~~~~
```

That is somewhat expected, as [`NamedTuple` subclasses is flagged as `wontfix` by Python's `typing` project](https://github.com/python/typing/issues/427).

@janluke, would you be open to change the type of `HelpTheme` so I can reuse it seamlessly?

I naively think that a class is the natural choice, but maybe a `@dataclass` might be another alternative to `NamedTuple`. I'm pretty sure you have a better idea of what `HelpTheme` should look like in that case.

### PR DESCRIPTION
**Pull request by janluke**
Fixes #159.
- #159 

@kdeldycke Does this solve your issue?

### CODE REVIEW

**Comment by kdeldycke** [comment]
I tried to directly inherits from your new `HelpTheme` dataclass, but of course this is not allowed:

`TypeError: cannot inherit non-frozen dataclass from a frozen one` 😅

**Comment by janluke** [comment]
Do you need it to be a non-frozen dataclass?

**Comment by kdeldycke** [comment]
> Do you need it to be a non-frozen dataclass?

Unfreezing it would allow me to streamline my code with:
```python
@dataclass
class HelpExtraTheme(cloup.HelpTheme):

    critical: IStyle = identity
    error: IStyle = identity
    warning: IStyle = identity
    info: IStyle = identity
    debug: IStyle = identity
    """Log levels from Python's logging module."""

    ...
```

Else I have to build up a new class programmatically out of `cloup.HelpTheme` fields.

Freezing that dataclass is tempting and I understand the appeal. But I guess that's not critical. I'm probably the only one on the planet trying to play with the internals of `cloup.HelpTheme`. So no need to protect me from myself! 😇 I'll take full responsibility and not blame you if I mess up! 😁

**Comment by janluke** [comment]
Sorry, it's still not clear to me why you can't
```python
@dataclass(frozen=True)
class HelpExtraTheme(cloup.HelpTheme):
    ...
```

**Comment by kdeldycke** [comment]
> Sorry, it's still not clear to me why you can't

Because I'm stupid! 😓

I apologize for the back and forth, I'm just discovering this implementation detail. You are right: it is indeed possible to subclass a frozen dataclass. All you need to make it frozen too. And mine wasn't.

Here is the proof:

```pycon
Python 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

>>> from dataclasses import dataclass

>>> @dataclass(frozen=True)
... class HelpTheme:
...     ...
... 

>>> HelpTheme
<class '__main__.HelpTheme'>

>>> @dataclass
... class HelpExtraTheme(HelpTheme):
...     ...
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File ".../python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/dataclasses.py", line 988, in _process_class
    raise TypeError('cannot inherit non-frozen dataclass from a '
TypeError: cannot inherit non-frozen dataclass from a frozen one

>>> @dataclass(frozen=True)
... class HelpExtraTheme(HelpTheme):
...     ...
... 

>>> HelpExtraTheme
<class '__main__. HelpExtraTheme'>
```

Just tried this branch against my code and it works! 🎉

See: https://github.com/kdeldycke/click-extra/pull/704/files

So yeah, you can merge this PR. LGTM!

**Comment by kdeldycke** [comment]
Also, I had to redefine the `with_` helper. My version is a little convoluted but generic. Feel free to adopt it if it makes sense for Cloup:  https://github.com/kdeldycke/click-extra/blob/f93cbc8ddfa8b8cc135f54474929bd74cf57ec7f/click_extra/colorize.py#L87-L109

**Comment by kdeldycke** [comment]
Thanks for the merge! 🎉

**Pull request merged**
